package com.microhelper.sysuser.persistent.model;

import java.util.Date;

public class SysDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_parent
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer deptParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.dept_discrption
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String deptDiscrption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dept.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_id
     *
     * @return the value of sys_dept.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_id
     *
     * @param deptId the value for sys_dept.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_name
     *
     * @return the value of sys_dept.dept_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_name
     *
     * @param deptName the value for sys_dept.dept_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_parent
     *
     * @return the value of sys_dept.dept_parent
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getDeptParent() {
        return deptParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_parent
     *
     * @param deptParent the value for sys_dept.dept_parent
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeptParent(Integer deptParent) {
        this.deptParent = deptParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.dept_discrption
     *
     * @return the value of sys_dept.dept_discrption
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getDeptDiscrption() {
        return deptDiscrption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.dept_discrption
     *
     * @param deptDiscrption the value for sys_dept.dept_discrption
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeptDiscrption(String deptDiscrption) {
        this.deptDiscrption = deptDiscrption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.delete_flag
     *
     * @return the value of sys_dept.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.delete_flag
     *
     * @param deleteFlag the value for sys_dept.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.create_user
     *
     * @return the value of sys_dept.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.create_user
     *
     * @param createUser the value for sys_dept.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.create_datetime
     *
     * @return the value of sys_dept.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.create_datetime
     *
     * @param createDatetime the value for sys_dept.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.update_user
     *
     * @return the value of sys_dept.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.update_user
     *
     * @param updateUser the value for sys_dept.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dept.update_time
     *
     * @return the value of sys_dept.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dept.update_time
     *
     * @param updateTime the value for sys_dept.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}