package com.microhelper.sysuser.persistent.model;

public class SysFunctionPage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_page.function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_page.function_en_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String functionEnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_page.function_cn_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String functionCnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_page.function_right
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String functionRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_function_page.function_discription
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String functionDiscription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_page.function_id
     *
     * @return the value of sys_function_page.function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_page.function_id
     *
     * @param functionId the value for sys_function_page.function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_page.function_en_name
     *
     * @return the value of sys_function_page.function_en_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getFunctionEnName() {
        return functionEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_page.function_en_name
     *
     * @param functionEnName the value for sys_function_page.function_en_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setFunctionEnName(String functionEnName) {
        this.functionEnName = functionEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_page.function_cn_name
     *
     * @return the value of sys_function_page.function_cn_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getFunctionCnName() {
        return functionCnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_page.function_cn_name
     *
     * @param functionCnName the value for sys_function_page.function_cn_name
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setFunctionCnName(String functionCnName) {
        this.functionCnName = functionCnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_page.function_right
     *
     * @return the value of sys_function_page.function_right
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getFunctionRight() {
        return functionRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_page.function_right
     *
     * @param functionRight the value for sys_function_page.function_right
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setFunctionRight(String functionRight) {
        this.functionRight = functionRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_function_page.function_discription
     *
     * @return the value of sys_function_page.function_discription
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getFunctionDiscription() {
        return functionDiscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_function_page.function_discription
     *
     * @param functionDiscription the value for sys_function_page.function_discription
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setFunctionDiscription(String functionDiscription) {
        this.functionDiscription = functionDiscription;
    }
}