package com.microhelper.sysuser.persistent.model;

import java.util.Date;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_cn
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String roleCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_en
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String roleEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_discription
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private String roleDiscription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_id
     *
     * @return the value of sys_role.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_id
     *
     * @param roleId the value for sys_role.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_cn
     *
     * @return the value of sys_role.role_cn
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getRoleCn() {
        return roleCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_cn
     *
     * @param roleCn the value for sys_role.role_cn
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setRoleCn(String roleCn) {
        this.roleCn = roleCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_en
     *
     * @return the value of sys_role.role_en
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getRoleEn() {
        return roleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_en
     *
     * @param roleEn the value for sys_role.role_en
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setRoleEn(String roleEn) {
        this.roleEn = roleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_discription
     *
     * @return the value of sys_role.role_discription
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public String getRoleDiscription() {
        return roleDiscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_discription
     *
     * @param roleDiscription the value for sys_role.role_discription
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setRoleDiscription(String roleDiscription) {
        this.roleDiscription = roleDiscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.dept_id
     *
     * @return the value of sys_role.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.dept_id
     *
     * @param deptId the value for sys_role.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.delete_flag
     *
     * @return the value of sys_role.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.delete_flag
     *
     * @param deleteFlag the value for sys_role.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_user
     *
     * @return the value of sys_role.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_user
     *
     * @param createUser the value for sys_role.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_datetime
     *
     * @return the value of sys_role.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_datetime
     *
     * @param createDatetime the value for sys_role.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.update_user
     *
     * @return the value of sys_role.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.update_user
     *
     * @param updateUser the value for sys_role.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.update_time
     *
     * @return the value of sys_role.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.update_time
     *
     * @param updateTime the value for sys_role.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}