package com.microhelper.sysuser.persistent.model;

public class SysRoleFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.role_function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer roleFunctionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_function.function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer functionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.role_function_id
     *
     * @return the value of sys_role_function.role_function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getRoleFunctionId() {
        return roleFunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.role_function_id
     *
     * @param roleFunctionId the value for sys_role_function.role_function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setRoleFunctionId(Integer roleFunctionId) {
        this.roleFunctionId = roleFunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.role_id
     *
     * @return the value of sys_role_function.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.role_id
     *
     * @param roleId the value for sys_role_function.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_function.function_id
     *
     * @return the value of sys_role_function.function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_function.function_id
     *
     * @param functionId the value for sys_role_function.function_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }
}