package com.microhelper.sysuser.persistent.model;

public class SysUserDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept.user_dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer userDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept.user_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_dept.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept.user_dept_id
     *
     * @return the value of sys_user_dept.user_dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getUserDeptId() {
        return userDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept.user_dept_id
     *
     * @param userDeptId the value for sys_user_dept.user_dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUserDeptId(Integer userDeptId) {
        this.userDeptId = userDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept.user_id
     *
     * @return the value of sys_user_dept.user_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept.user_id
     *
     * @param userId the value for sys_user_dept.user_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_dept.dept_id
     *
     * @return the value of sys_user_dept.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_dept.dept_id
     *
     * @param deptId the value for sys_user_dept.dept_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}