package com.microhelper.sysuser.persistent.model;

import java.util.Date;

public class SysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.user_role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.user_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.user_role_id
     *
     * @return the value of sys_user_role.user_role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.user_role_id
     *
     * @param userRoleId the value for sys_user_role.user_role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.user_id
     *
     * @return the value of sys_user_role.user_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.user_id
     *
     * @param userId the value for sys_user_role.user_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.role_id
     *
     * @return the value of sys_user_role.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.role_id
     *
     * @param roleId the value for sys_user_role.role_id
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.delete_flag
     *
     * @return the value of sys_user_role.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.delete_flag
     *
     * @param deleteFlag the value for sys_user_role.delete_flag
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.create_user
     *
     * @return the value of sys_user_role.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.create_user
     *
     * @param createUser the value for sys_user_role.create_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.create_datetime
     *
     * @return the value of sys_user_role.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.create_datetime
     *
     * @param createDatetime the value for sys_user_role.create_datetime
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.update_user
     *
     * @return the value of sys_user_role.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.update_user
     *
     * @param updateUser the value for sys_user_role.update_user
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.update_time
     *
     * @return the value of sys_user_role.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.update_time
     *
     * @param updateTime the value for sys_user_role.update_time
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}