package com.microhelper.sysuser.persistent.mapper;

import com.microhelper.sysuser.persistent.model.SysFunctionPage;

public interface SysFunctionPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function_page
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    int deleteByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function_page
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    int insert(SysFunctionPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function_page
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    int insertSelective(SysFunctionPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function_page
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    SysFunctionPage selectByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function_page
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    int updateByPrimaryKeySelective(SysFunctionPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_function_page
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    int updateByPrimaryKey(SysFunctionPage record);
}