package com.microhelper.sysuser.persistent.mapper;

import com.microhelper.sysuser.persistent.model.SysRoleFunction;

public interface SysRoleFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    int insert(SysRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_function
     *
     * @mbggenerated Mon Apr 13 20:56:34 CST 2020
     */
    int insertSelective(SysRoleFunction record);
}